name: Build

on:
    push:
        branches-ignore:
            - 'dependabot/**'
    pull_request: ~
    release:
        types: [ created ]
    schedule:
        -   cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install PHP dependencies
                run: composer install --no-interaction
